<?php

/**
 * @file
 * Contains myrdvdoctor.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function myrdvdoctor_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the myrdvdoctor module.
    case 'help.page.myrdvdoctor':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function myrdvdoctor_theme() {
  return [
    'myrdvdoctor' => [
      'template' => 'myrdvdoctor',
      'render element' => 'children',
    ],
  ];
}
